import React, { useState, useEffect, useRef } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, Alert, Image, Modal, Switch, ScrollView } from 'react-native';
import * as Location from 'expo-location';
import AsyncStorage from '@react-native-async-storage/async-storage';
let BannerAd, BannerAdSize, MobileAds;
try{ const A=require('react-native-google-mobile-ads'); BannerAd=A.BannerAd; BannerAdSize=A.BannerAdSize; MobileAds=A.MobileAds; }catch(e){}
const BANNER_ID = __DEV__? "ca-app-pub-3940256099942544/6300978111" : "ca-app-pub-9890149028563226/7083933962";
const TRACKS=[{id:'zic',name:'珠海國際賽車場',en:'Zhuhai Circuit',short:'ZIC • ZHUHAI • 14T',lat:22.3598,lng:113.5678,img:require('./assets/tracks/zic.jpg')},{id:'gic',name:'廣東國際賽車場',en:'Guangdong Circuit',short:'GIC • 13T',lat:23.1216,lng:112.559,img:require('./assets/tracks/gic.jpg')},{id:'fuji',name:'富士賽道',en:'Fuji Speedway',short:'FUJI • 16T',lat:35.3717,lng:138.927,img:require('./assets/tracks/fuji.jpg')},{id:'suzuka',name:'鈴鹿賽道',en:'Suzuka Circuit',short:'SUZUKA • 18T',lat:34.8431,lng:136.5409,img:require('./assets/tracks/suzuka.jpg')},{id:'tsukuba',name:'筑波賽道',en:'Tsukuba Circuit',short:'TSUKUBA • 9T',lat:36.083,lng:140.075,img:require('./assets/tracks/tsukuba.jpg')},{id:'okayama',name:'岡山國際賽道',en:'Okayama Circuit',short:'OKAYAMA • 11T',lat:34.915,lng:134.212,img:require('./assets/tracks/okayama.jpg')},{id:'buriram',name:'武里南賽道',en:'Buriram Circuit',short:'BURIRAM • 12T',lat:14.966,lng:103.095,img:require('./assets/tracks/buriram.jpg')},{id:'sepang',name:'雪邦賽道',en:'Sepang Circuit',short:'SEPANG • 15T',lat:2.7606,lng:101.738,img:require('./assets/tracks/sepang.jpg')},{id:'zhuzhou',name:'株洲國際賽道',en:'Zhuzhou Circuit',short:'ZHUZHOU • 14T',lat:27.85,lng:113.15,img:require('./assets/tracks/zhuzhou.jpg')},{id:'ningbo',name:'寧波國際賽道',en:'Ningbo Circuit',short:'NINGBO • 22T',lat:30.33,lng:121.45,img:require('./assets/tracks/ningbo.jpg')},{id:'guia',name:'東望洋賽道',en:'Guia Circuit',short:'GUIA • MACAU • 22T',lat:22.197,lng:113.555,img:require('./assets/tracks/guia.jpg')}];
const LANG={zh:{app:'圈速go',gpsOk:'● GPS已鎖定',gpsNo:'○ 搜尋中...',acc:'精度',speed:'速度',prev:'上一圈',best:'最佳',delta:'Delta',live:'LIVE',sf:'起/終點',s1:'S1',s2:'S2',s3:'S3',hist:'圈速紀錄 (5圈)',dash:'儀表',sess:'紀錄',tracks:'賽道',set:'設定',timer:'--- 計時 ---',disp:'--- 顯示 ---',sys:'--- 系統 ---',proF:'--- Pro功能',night:'夜間模式',unit:'單位 km/h↔mph',keep:'螢幕常亮',dot:'即時紅點',langTitle:'語言 中 / EN',export:'匯出CSV/GPX',ghost:'幽靈線透明度',clear:'清除紀錄',ver:'版本 v1.0',proFree:'免費版',proOn:'已啟用',proDesc:'10圈自動刪舊 • Pro100圈 • 幽靈線 • 無廣告',upgrade:'升級 Pro $38',calib:'起/終點校準',minTrig:'最低觸發',autoLap:'自動計圈',gLat:'橫向G',gMax:'最大G',needPro:'Pro功能',needProDesc:'幽靈線為Pro功能，請升級Pro $38'},en:{app:'LapGo',gpsOk:'● GPS Locked',gpsNo:'○ Searching...',acc:'Acc',speed:'Speed',prev:'Prev',best:'Best',delta:'Delta',live:'LIVE',sf:'S/F',s1:'S1',s2:'S2',s3:'S3',hist:'Lap History (5)',dash:'Dash',sess:'Logs',tracks:'Tracks',set:'Settings',timer:'--- Timer ---',disp:'--- Display ---',sys:'--- System ---',proF:'--- Pro ---',night:'Night Mode',unit:'Unit km/h↔mph',keep:'Keep Screen On',dot:'Live Dot',langTitle:'Language 中 / EN',export:'Export CSV/GPX',ghost:'Ghost Opacity',clear:'Clear All',ver:'Version v1.0',proFree:'Free',proOn:'Active',proDesc:'Free 10 laps • Pro 100 • Ghost • No Ads',upgrade:'Upgrade Pro $38',calib:'S/F Calib',minTrig:'Min Trigger',autoLap:'Auto Lap',gLat:'Lat G',gMax:'Max G',needPro:'Pro Feature',needProDesc:'Ghost line is Pro feature. Please Upgrade Pro $38'}};
function dist(a,b,c,d){const R=6371000;const dLat=(c-a)*Math.PI/180;const dLng=(d-b)*Math.PI/180;const x=Math.sin(dLat/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}export default function App(){
const [track,setTrack]=useState(TRACKS[0]);const [locked,setLocked]=useState(false);const [acc,setAcc]=useState(0);const [speedMs,setSpeedMs]=useState(0);
const [running,setRunning]=useState(false);const [cur,setCur]=useState(0);const [best,setBest]=useState(null);const [prev,setPrev]=useState(null);
const [sector,setSector]=useState([0,0,0]);const [history,setHistory]=useState([]);const [isPro,setIsPro]=useState(false);const [progress,setProgress]=useState(0);const [tab,setTab]=useState('dash');
const [showSet,setShowSet]=useState(false);const [keepOn,setKeepOn]=useState(true);const [darkMode,setDarkMode]=useState(true);const [lang,setLang]=useState('zh');
const [calibDist,setCalibDist]=useState(25);const [minTrigger,setMinTrigger]=useState(15);const [autoLap,setAutoLap]=useState(true);const [unit,setUnit]=useState('kmh');const [liveDot,setLiveDot]=useState(true);const [ghostOp,setGhostOp]=useState(0.5);const [gForce,setGForce]=useState({x:0,max:0});
const startRef=useRef(0);const timerRef=useRef(null);const subRef=useRef(null);const lastSpeed=useRef(0);const T=LANG[lang];
useEffect(()=>{(async()=>{
try{if(MobileAds)await MobileAds().initialize();}catch(e){}
const {status}=await Location.requestForegroundPermissionsAsync();if(status!=='granted')return;await Location.requestBackgroundPermissionsAsync();
const vals=await AsyncStorage.multiGet(['lap_history','isPro','darkMode','lang','calib','minTrig','autoLap','unit','liveDot','ghostOp']);const m=Object.fromEntries(vals);
if(m.lap_history)setHistory(JSON.parse(m.lap_history));if(m.isPro)setIsPro(true);if(m.darkMode!==null)setDarkMode(m.darkMode==='1');if(m.lang)setLang(m.lang);
if(m.calib)setCalibDist(parseInt(m.calib));if(m.minTrig)setMinTrigger(parseInt(m.minTrig));if(m.autoLap!==null)setAutoLap(m.autoLap==='1');if(m.unit)setUnit(m.unit);if(m.liveDot!==null)setLiveDot(m.liveDot==='1');if(m.ghostOp)setGhostOp(parseFloat(m.ghostOp));
subRef.current=await Location.watchPositionAsync({accuracy:Location.Accuracy.BestForNavigation,distanceInterval:1,timeInterval:300},loc=>{
setAcc(loc.coords.accuracy||0);setLocked(true);setSpeedMs(loc.coords.speed||0);
const g=Math.abs((loc.coords.speed||0)-lastSpeed.current)*0.8;lastSpeed.current=loc.coords.speed||0;setGForce(p=>({x:g.toFixed(2),max:Math.max(g,p.max).toFixed(2)}));
let near=TRACKS[0],min=Infinity;TRACKS.forEach(t=>{const dd=dist(loc.coords.latitude,loc.coords.longitude,t.lat,t.lng);if(dd<min){min=dd;near=t;}});
if(min<50000&&!running&&near.id!==track.id)setTrack(near);
if(running&&autoLap){setProgress(((Date.now()-startRef.current)/1000%92)/92);if(dist(loc.coords.latitude,loc.coords.longitude,track.lat,track.lng)<calibDist&&Date.now()-startRef.current>minTrigger*1000)finish();}});
})();return()=>{if(subRef.current)subRef.current.remove();if(timerRef.current)clearInterval(timerRef.current);};},[track,running,calibDist,minTrigger,autoLap]);
const fmt=s=>{if(!s)return '--:--.--';const mm=Math.floor(s/60);const r=(s%60).toFixed(2);return `${mm}:${r.padStart(5,'0')}`;};const getSpeed=()=>{const kmh=speedMs*3.6;return unit==='kmh'?kmh.toFixed(0):(kmh*0.621371).toFixed(0);};
const start=()=>{startRef.current=Date.now();setRunning(true);setGForce({x:0,max:0});timerRef.current=setInterval(()=>setCur((Date.now()-startRef.current)/1000),100);};const stop=()=>{setRunning(false);clearInterval(timerRef.current);};
const finish=async()=>{const t=(Date.now()-startRef.current)/1000;const s1=t*0.35,s2=t*0.34,s3=t*0.31;const lap={id:Date.now(),time:t,s1,s2,s3,track:track.id,date:new Date().toISOString(),gMax:gForce.max};let nh=[lap,...history];if(!isPro&&nh.length>10)nh=nh.slice(0,10);if(isPro&&nh.length>100)nh=nh.slice(0,100);setHistory(nh);await AsyncStorage.setItem('lap_history',JSON.stringify(nh));setPrev(t);if(!best||t<best)setBest(t);setSector([s1,s2,s3]);startRef.current=Date.now();};
const save=async(k,v)=>{await AsyncStorage.setItem(k,String(v));};const theme=darkMode?darkS:lightS;
const toggleLang=async()=>{const nl=lang==='zh'?'en':'zh';setLang(nl);await save('lang',nl);};
const toggleUnit=async()=>{const nu=unit==='kmh'?'mph':'kmh';setUnit(nu);await save('unit',nu);};
const handleGhost=()=>{if(!isPro){Alert.alert(T.needPro,T.needProDesc,[{text:lang==='zh'?'稍後':'Later',style:'cancel'},{text:T.upgrade,onPress:async()=>{setIsPro(true);await AsyncStorage.setItem('isPro','1');}}]);return;}const nv=ghostOp>=1?0.1:ghostOp+0.1;setGhostOp(parseFloat(nv.toFixed(1)));save('ghostOp',nv.toFixed(1));};
const DashView=()=>(
<ScrollView style={{flex:1}} contentContainerStyle={{paddingBottom:6}} showsVerticalScrollIndicator={false}>
<Text style={[s.big,theme.t]}>{fmt(cur)}</Text>
<View style={s.row3}><View style={[s.b,theme.b]}><Text style={[s.l,theme.sub]}>{T.prev}</Text><Text style={[s.v,theme.t]}>{prev?fmt(prev):'--'}</Text></View><View style={[s.b,theme.b]}><Text style={[s.l,theme.sub]}>{T.best}</Text><Text style={[s.v,{color:'#00cc66'}]}>{best?fmt(best):'--'}</Text></View><View style={[s.b,theme.b]}><Text style={[s.l,theme.sub]}>{T.delta}</Text><Text style={[s.v,{color:'#00cc66'}]}>{prev&&best?`${(prev-best).toFixed(2)}`:'--'}</Text></View></View>
<View style={{flexDirection:'row',marginHorizontal:6,marginTop:4}}><View style={[s.dataBox,theme.b,{flex:1}]}><Text style={s.dataLabel}>{T.speed} ({unit})</Text><Text style={[s.dataVal,{color:'#00e5ff'}]}>{getSpeed()} <Text style={{fontSize:10}}>{unit}</Text></Text></View><View style={[s.dataBox,theme.b,{flex:1.2}]}><Text style={s.dataLabel}>G-FORCE</Text><View style={{flexDirection:'row',justifyContent:'space-around',alignItems:'center'}}><Text style={{color:'#ffaa00',fontWeight:'bold',fontSize:11}}>{gForce.x}G</Text><View style={{width:28,height:28,borderRadius:14,borderWidth:1,borderColor:'#333',backgroundColor:'#0a0a0a',justifyContent:'center',alignItems:'center'}}><View style={{width:6,height:6,borderRadius:3,backgroundColor:'#ff3333',transform:[{translateX:parseFloat(gForce.x)*5}]}}/></View><Text style={{color:'#fff',fontWeight:'bold',fontSize:11}}>{gForce.max}G</Text></View></View></View>
<View style={[s.mapFixed,theme.map]}><Image source={track.img} style={s.mapImgFixed} resizeMode="cover"/>{liveDot&&<View style={[s.dot,{left:`${12+progress*70}%`,top:`${30+Math.sin(progress*6)*18}%`}]}/>}{isPro&&liveDot&&<View style={[s.ghost,{opacity:ghostOp,left:`${16+progress*66}%`,top:`${34+Math.sin(progress*6)*16}%`}]}/>}<Text style={s.live}>LIVE</Text><Text style={s.start}>{T.sf} • {track.short}</Text></View>
<View style={s.row3}><View style={[s.sb,theme.b]}><Text style={[s.sbT,theme.t]}>{sector[0].toFixed(2)}</Text><Text style={s.sL}>{T.s1}</Text></View><View style={[s.sb,theme.b]}><Text style={[s.sbT,theme.t]}>{sector[1].toFixed(2)}</Text><Text style={s.sL}>{T.s2}</Text></View><View style={[s.sb,theme.b]}><Text style={[s.sbT,theme.t]}>{sector[2].toFixed(2)}</Text><Text style={s.sL}>{T.s3}</Text></View></View>
<Text style={[s.hT,theme.t]}>{T.hist}</Text><View style={{minHeight:80}}>{history.slice(0,5).map((h,i)=><View key={h.id} style={[s.hR,theme.b]}><Text style={[theme.t,{fontSize:10}]}>Lap {history.length-i} • {fmt(h.time)} • {h.track.toUpperCase()} • {h.gMax||0}G</Text></View>)}{history.length===0&&<Text style={[s.sub,{textAlign:'center',marginTop:6}]}>No laps</Text>}</View>
<View style={s.btnR}><TouchableOpacity style={[s.btn,{backgroundColor:'#ff3333'}]} onPress={stop}><Text style={s.btnT}>■ STOP</Text></TouchableOpacity><TouchableOpacity style={[s.btn,{backgroundColor:'#00cc66'}]} onPress={start}><Text style={s.btnT}>▶ START</Text></TouchableOpacity></View>
{!isPro&&BannerAd&&<View style={{height:52,backgroundColor:'#000',justifyContent:'center'}}><BannerAd unitId={BANNER_ID} size={BannerAdSize.BANNER} /></View>}
</ScrollView>
);
return(
<View style={[s.c,theme.c]}>
<View style={[s.head,theme.head]}><View style={{flex:1}}><Text style={[s.t,theme.t]}>{T.app}</Text><Text style={[s.sub,theme.sub]} numberOfLines={1}>{lang==='zh'?track.name:track.en} • {track.short}</Text></View><TouchableOpacity onPress={()=>setShowSet(true)} style={s.gear}><Text style={{fontSize:16}}>⚙️</Text></TouchableOpacity></View>
<View style={[s.gps,theme.gps]}><Text style={{color:locked?'#00cc66':'#ff4444',fontWeight:'bold',fontSize:10}}>{locked?T.gpsOk:T.gpsNo}</Text><Text style={[s.gpsI,theme.sub]}>{T.acc} {acc.toFixed(1)}m</Text></View>
<View style={{flex:1}}>
{tab==='dash'&&<DashView/>}
{tab==='sessions'&&<ScrollView style={{flex:1,padding:6}}>{history.map((h,i)=><View key={h.id} style={[s.hR,theme.b]}><Text style={[theme.t,{fontSize:10}]}>{history.length-i}. {h.track.toUpperCase()} • {fmt(h.time)} • {h.gMax||0}G</Text></View>)}{history.length===0&&<Text style={[theme.sub,{textAlign:'center',marginTop:20}]}>未有紀錄</Text>}</ScrollView>}
{tab==='tracks'&&<ScrollView style={{flex:1}} contentContainerStyle={{flexDirection:'row',flexWrap:'wrap',padding:6}}>{TRACKS.map(t=><TouchableOpacity key={t.id} onPress={()=>{setTrack(t);setTab('dash');}} style={[s.trackCard,theme.b,track.id===t.id&&{borderColor:'#00cc66',borderWidth:2}]}><Image source={t.img} style={{width:'100%',height:72,borderRadius:6}} resizeMode="cover"/><Text style={[theme.t,{fontSize:9,marginTop:3}]}>{lang==='zh'?t.name:t.en}</Text></TouchableOpacity>)}</ScrollView>}
</View><Modal visible={showSet} animationType="slide"><View style={[s.setPage,theme.c]}><ScrollView style={{padding:14,marginTop:28}}><View style={{flexDirection:'row',justifyContent:'space-between',marginBottom:8}}><Text style={[{fontSize:15,fontWeight:'bold'},theme.t]}>{T.set}</Text><TouchableOpacity onPress={()=>setShowSet(false)}><Text style={[{fontSize:18},theme.t]}>✕</Text></TouchableOpacity></View>
<View style={[s.proCard,isPro&&{backgroundColor:'#111'}]}><Text style={{fontWeight:'bold',color:isPro?'#ffaa00':'#111',fontSize:12}}>👑 {isPro?T.proOn:T.proFree}</Text><Text style={{fontSize:9,color:isPro?'#fff':'#666',marginTop:2}}>{T.proDesc}</Text>{!isPro&&<TouchableOpacity style={s.upBtn} onPress={async()=>{setIsPro(true);await AsyncStorage.setItem('isPro','1');Alert.alert('已升級Pro');}}><Text style={{color:'#fff',fontWeight:'bold',textAlign:'center',fontSize:11}}>{T.upgrade}</Text></TouchableOpacity>}</View>
<Text style={[s.setTitle,theme.t]}>{T.timer}</Text>
<TouchableOpacity style={[s.setRow,theme.b]} onPress={()=>{const nv=calibDist>=50?10:calibDist+5;setCalibDist(nv);save('calib',nv);}}><Text style={theme.t}>{T.calib} {calibDist}m</Text><Text style={theme.sub}>＞ {calibDist}m</Text></TouchableOpacity>
<TouchableOpacity style={[s.setRow,theme.b]} onPress={()=>{const nv=minTrigger>=30?5:minTrigger+5;setMinTrigger(nv);save('minTrig',nv);}}><Text style={theme.t}>{T.minTrig} {minTrigger}s</Text><Text style={theme.sub}>＞ {minTrigger}s</Text></TouchableOpacity>
<View style={[s.setRow,theme.b]}><Text style={theme.t}>{T.autoLap}</Text><Switch value={autoLap} onValueChange={v=>{setAutoLap(v);save('autoLap',v?'1':'0');}}/></View>
<Text style={[s.setTitle,theme.t]}>{T.disp}</Text>
<View style={[s.setRow,theme.b]}><Text style={theme.t}>{T.night}</Text><Switch value={darkMode} onValueChange={v=>{setDarkMode(v);save('darkMode',v?'1':'0');}}/></View>
<View style={[s.setRow,theme.b]}><Text style={theme.t}>{T.dot}</Text><Switch value={liveDot} onValueChange={v=>{setLiveDot(v);save('liveDot',v?'1':'0');}}/></View>
<TouchableOpacity style={[s.setRow,theme.b]} onPress={toggleLang}><Text style={theme.t}>{T.langTitle}</Text><Text style={[theme.t,{fontWeight:'bold',color:'#00cc66'}]}>{lang==='zh'?'中文':'EN'} ↔</Text></TouchableOpacity>
<TouchableOpacity style={[s.setRow,theme.b]} onPress={toggleUnit}><Text style={theme.t}>{T.unit}</Text><Text style={[theme.t,{fontWeight:'bold',color:'#00cc66'}]}>{unit.toUpperCase()} ↔</Text></TouchableOpacity>
<Text style={[s.setTitle,theme.t]}>{T.proF}</Text>
<TouchableOpacity style={[s.setRow,theme.b]} onPress={handleGhost}><Text style={theme.t}>{T.ghost} {Math.round(ghostOp*100)}%</Text><Text style={theme.sub}>{isPro?'＞':'🔒 Pro'}</Text></TouchableOpacity>
<Text style={[s.setTitle,theme.t]}>{T.sys}</Text>
<TouchableOpacity style={[s.setRow,theme.b]} onPress={async()=>{await AsyncStorage.multiRemove(['lap_history','isPro']);setHistory([]);setIsPro(false);}}><Text style={theme.t}>{T.clear}</Text></TouchableOpacity>
<View style={[s.setRow,theme.b]}><Text style={[theme.t,{fontSize:10,color:'#888'}]}>{T.ver}</Text><Text style={{fontSize:9,color:'#555'}}>com.lapgo.timer</Text></View>
</ScrollView></View></Modal>
<View style={[s.tabBar,theme.gps]}><TouchableOpacity style={s.tabBtn} onPress={()=>setTab('dash')}><Text style={[s.tab,tab==='dash'&&s.tabOn]}>{T.dash}</Text></TouchableOpacity><TouchableOpacity style={s.tabBtn} onPress={()=>setTab('sessions')}><Text style={[s.tab,tab==='sessions'&&s.tabOn]}>{T.sess}</Text></TouchableOpacity><TouchableOpacity style={s.tabBtn} onPress={()=>setTab('tracks')}><Text style={[s.tab,tab==='tracks'&&s.tabOn]}>{T.tracks}</Text></TouchableOpacity></View>
</View>);
  }const s=StyleSheet.create({c:{flex:1,paddingTop:0},head:{flexDirection:'row',justifyContent:'space-between',paddingHorizontal:10,paddingTop:32,paddingBottom:4,alignItems:'center'},t:{fontSize:15,fontWeight:'bold'},sub:{fontSize:10},gear:{padding:4},proCard:{backgroundColor:'#fff3cd',padding:8,borderRadius:8,marginTop:6,borderWidth:1,borderColor:'#ffaa00'},upBtn:{backgroundColor:'#111',padding:7,borderRadius:6,marginTop:5},gps:{flexDirection:'row',justifyContent:'space-between',paddingHorizontal:10,paddingVertical:3},gpsI:{fontSize:9},big:{fontSize:42,textAlign:'center',fontWeight:'bold',marginVertical:2},row3:{flexDirection:'row',justifyContent:'space-around'},b:{padding:5,borderRadius:6,flex:1,margin:2,alignItems:'center',borderWidth:1},l:{fontSize:8},v:{fontSize:12,fontWeight:'bold'},dataBox:{padding:5,borderRadius:6,margin:2,borderWidth:1},dataLabel:{fontSize:8,color:'#888'},dataVal:{fontSize:16,fontWeight:'bold'},mapFixed:{height:158,marginHorizontal:6,marginVertical:4,borderRadius:10,overflow:'hidden',borderWidth:1,backgroundColor:'#000'},mapImgFixed:{width:'100%',height:'100%'},dot:{position:'absolute',width:10,height:10,borderRadius:5,backgroundColor:'#ff3333',borderWidth:1.5,borderColor:'#fff',zIndex:2},ghost:{position:'absolute',width:8,height:8,borderRadius:4,backgroundColor:'#00ff88',borderWidth:1,borderColor:'#fff',zIndex:1},live:{position:'absolute',right:5,top:5,color:'#ff0000',fontSize:7,fontWeight:'bold',backgroundColor:'#fff',paddingHorizontal:3,paddingVertical:1,borderRadius:3},start:{position:'absolute',bottom:5,left:6,color:'#fff',fontSize:8,backgroundColor:'rgba(0,0,0,0.7)',paddingHorizontal:5,paddingVertical:2,borderRadius:4},sb:{padding:4,borderRadius:5,flex:1,margin:2,alignItems:'center',borderWidth:1},sbT:{fontSize:10,fontWeight:'bold'},sL:{backgroundColor:'#00cc66',color:'#fff',paddingHorizontal:5,borderRadius:3,marginTop:1,fontSize:8},hT:{fontSize:11,marginHorizontal:8,marginTop:4,fontWeight:'bold'},hR:{padding:6,marginHorizontal:6,marginVertical:2,borderRadius:5,borderWidth:1},btnR:{flexDirection:'row',justifyContent:'space-around',marginHorizontal:8,marginVertical:6},btn:{padding:10,borderRadius:7,flex:1,margin:2,alignItems:'center'},btnT:{color:'#fff',fontWeight:'bold',fontSize:11},tabBar:{flexDirection:'row',justifyContent:'space-around',paddingVertical:10,borderTopWidth:1},tabBtn:{flex:1,alignItems:'center'},tab:{color:'#888',fontSize:11},tabOn:{color:'#00cc66',fontWeight:'bold',fontSize:12},setPage:{flex:1},setTitle:{fontWeight:'bold',marginTop:10,marginBottom:4,fontSize:10},setRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',padding:12,borderRadius:8,marginBottom:6,borderWidth:1},trackCard:{width:'47%',margin:'1.5%',padding:6,borderRadius:8,borderWidth:1}});
const lightS=StyleSheet.create({c:{backgroundColor:'#f5f5f5'},head:{backgroundColor:'#fff'},t:{color:'#111'},sub:{color:'#666'},gps:{backgroundColor:'#eee',borderTopWidth:1,borderColor:'#ddd'},b:{backgroundColor:'#fff',borderColor:'#e0e0e0'},map:{backgroundColor:'#000',borderColor:'#333'}});
const darkS=StyleSheet.create({c:{backgroundColor:'#000'},head:{backgroundColor:'#000'},t:{color:'#fff'},sub:{color:'#aaa'},gps:{backgroundColor:'#111',borderTopWidth:1,borderColor:'#333'},b:{backgroundColor:'#111',borderColor:'#333'},map:{backgroundColor:'#000',borderColor:'#333'}});
