import React, { useState, useEffect, useRef } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, Pressable, Alert, Image, Modal, Switch, ScrollView } from 'react-native';
import * as Location from 'expo-location';
import AsyncStorage from '@react-native-async-storage/async-storage';
let BannerAd, BannerAdSize, MobileAds;
try{ const A=require('react-native-google-mobile-ads'); BannerAd=A.BannerAd; BannerAdSize=A.BannerAdSize; MobileAds=A.MobileAds; }catch(e){}
const BANNER_ID = __DEV__? "ca-app-pub-3940256099942544/6300978111" : "ca-app-pub-9890149028563226/7083933962";
const TRACKS=[{id:'zic',name:'珠海國際賽車場',en:'Zhuhai Circuit',short:'ZIC • ZHUHAI • 14T',lat:22.3598,lng:113.5678,img:require('./assets/tracks/zic.jpg')},{id:'gic',name:'廣東國際賽車場',en:'Guangdong Circuit',short:'GIC • 13T',lat:23.1216,lng:112.559,img:require('./assets/tracks/gic.jpg')},{id:'fuji',name:'富士賽道',en:'Fuji Speedway',short:'FUJI • 16T',lat:35.3717,lng:138.927,img:require('./assets/tracks/fuji.jpg')},{id:'suzuka',name:'鈴鹿賽道',en:'Suzuka Circuit',short:'SUZUKA • 18T',lat:34.8431,lng:136.5409,img:require('./assets/tracks/suzuka.jpg')},{id:'tsukuba',name:'筑波賽道',en:'Tsukuba Circuit',short:'TSUKUBA • 9T',lat:36.083,lng:140.075,img:require('./assets/tracks/tsukuba.jpg')},{id:'okayama',name:'岡山國際賽道',en:'Okayama Circuit',short:'OKAYAMA • 11T',lat:34.915,lng:134.212,img:require('./assets/tracks/okayama.jpg')},{id:'buriram',name:'武里南賽道',en:'Buriram Circuit',short:'BURIRAM • 12T',lat:14.966,lng:103.095,img:require('./assets/tracks/buriram.jpg')},{id:'sepang',name:'雪邦賽道',en:'Sepang Circuit',short:'SEPANG • 15T',lat:2.7606,lng:101.738,img:require('./assets/tracks/sepang.jpg')},{id:'zhuzhou',name:'株洲國際賽道',en:'Zhuzhou Circuit',short:'ZHUZHOU • 14T',lat:27.85,lng:113.15,img:require('./assets/tracks/zhuzhou.jpg')},{id:'ningbo',name:'寧波國際賽道',en:'Ningbo Circuit',short:'NINGBO • 22T',lat:30.33,lng:121.45,img:require('./assets/tracks/ningbo.jpg')},{id:'guia',name:'東望洋賽道',en:'Guia Circuit',short:'GUIA • MACAU • 22T',lat:22.197,lng:113.555,img:require('./assets/tracks/guia.jpg')},{id:'tmn',name:'屯門公路 (荃灣→屯門)',en:'Tuen Mun Rd (TW→TM)',short:'TMR • 荃→屯 • 限速70',lat:22.3905,lng:113.9768,img:require('./assets/tracks/tuenmun-north.jpg')},{id:'tms',name:'屯門公路 (屯門→荃灣)',en:'Tuen Mun Rd (TM→TW)',short:'TMR • 屯→荃 • 限速70',lat:22.3741,lng:113.9585,img:require('./assets/tracks/tuenmun-south.jpg')}];
const ZIC_KEYS_V3=[[0.42,0.845],[0.36,0.842],[0.28,0.835],[0.20,0.815],[0.16,0.76],[0.14,0.68],[0.15,0.60],[0.20,0.54],[0.28,0.50],[0.35,0.48],[0.42,0.465],[0.48,0.43],[0.53,0.38],[0.58,0.32],[0.60,0.27],[0.56,0.24],[0.49,0.32],[0.46,0.38],[0.48,0.44],[0.54,0.46],[0.61,0.44],[0.68,0.35],[0.74,0.26],[0.79,0.24],[0.82,0.29],[0.79,0.36],[0.73,0.46],[0.68,0.55],[0.61,0.64],[0.53,0.73],[0.46,0.81],[0.42,0.845]];
function genPath(keys,n){const segs=[];let total=0;for(let i=0;i<keys.length-1;i++){const d=Math.hypot(keys[i+1][0]-keys[i][0],keys[i+1][1]-keys[i][1]);segs.push(d);total+=d;}const out=[];let segIdx=0,cur=0;for(let i=0;i<n;i++){const target=i/n*total;while(segIdx<segs.length-1&&cur+segs[segIdx]<target){cur+=segs[segIdx];segIdx++;}const r=segs[segIdx]?(target-cur)/segs[segIdx]:0;const a=keys[segIdx],b=keys[segIdx+1];out.push([a[0]+(b[0]-a[0])*r,a[1]+(b[1]-a[1])*r]);}return out;}
const ZIC_PATH=genPath(ZIC_KEYS_V3,97);
const TRACK_PATHS={zic:ZIC_PATH,gic:ZIC_PATH,fuji:ZIC_PATH,suzuka:ZIC_PATH,tsukuba:ZIC_PATH,okayama:ZIC_PATH,buriram:ZIC_PATH,sepang:ZIC_PATH,zhuzhou:ZIC_PATH,ningbo:ZIC_PATH,guia:ZIC_PATH,tmn:ZIC_PATH,tms:ZIC_PATH};
const LANG={zh:{app:'圈速go [DEMO V3貼線]',gpsOk:'● GPS已鎖定',gpsNo:'○ 搜尋中...',acc:'精度',speed:'速度',temp:'氣溫',prev:'上一圈',best:'最佳',delta:'Delta',sf:'起/終點',s1:'S1',s2:'S2',s3:'S3',hist:'圈速紀錄',dash:'儀表',sess:'紀錄',tracks:'賽道',set:'設定',timer:'--- 計時 ---',disp:'--- 顯示 ---',sys:'--- 系統 ---',proF:'--- Pro功能',night:'夜間模式',unit:'速度單位',tempUnit:'溫度單位',timeFmt:'時間制式',dot:'即時紅點',langTitle:'語言',ghost:'幽靈線透明度',clear:'清除紀錄',ver:'v1.0 V3',proFree:'免費版',proOn:'Pro已啟用 (V3貼線)',proDesc:'V3已解鎖紅點+幽靈 • 貼線唔出界',upgrade:'訂閱 Pro $38/月',calib:'起/終點校準',minTrig:'最低觸發',autoLap:'自動計圈',needPro:'即將推出',needProDesc:'更多Pro功能即將推出',gpsHz:'GPS頻率',accFilt:'精度過濾',labels:'賽道標籤',safeMode:'安全模式',about:'--- 關於 ---',disclaimer:'免責聲明',privacy:'私隱政策',contact:'聯絡我',disTxt:'本App僅供賽道日及訓練參考',priTxt:'本App不會收集個人位置數據',conTxt:'fungfung842@gmail.com'},en:{app:'LapGo V3',gpsOk:'● GPS Locked',gpsNo:'○ Searching...',acc:'Acc',speed:'Speed',temp:'Temp',prev:'Prev',best:'Best',delta:'Delta',sf:'S/F',s1:'S1',s2:'S2',s3:'S3',hist:'Lap History',dash:'Dash',sess:'Logs',tracks:'Tracks',set:'Settings',timer:'--- Timer ---',disp:'--- Display ---',sys:'--- System ---',proF:'--- Pro ---',night:'Night Mode',unit:'Speed Unit',tempUnit:'Temp Unit',timeFmt:'Time Format',dot:'Live Dot',langTitle:'Language',ghost:'Ghost Opacity',clear:'Clear All',ver:'v1.0 V3',proFree:'Free',proOn:'Pro Active V3',proDesc:'V3 on-track',upgrade:'Subscribe Pro $38/mo',calib:'S/F Calib',minTrig:'Min Trigger',autoLap:'Auto Lap',needPro:'Coming Soon',needProDesc:'More Pro features coming',gpsHz:'GPS Rate',accFilt:'Accuracy Filter',labels:'Track Labels',safeMode:'Safe Mode',about:'--- About ---',disclaimer:'Disclaimer',privacy:'Privacy',contact:'Contact',disTxt:'For track day only',priTxt:'No location collected',conTxt:'Feedback'}};function dist(a,b,c,d){const R=6371000;const dLat=(c-a)*Math.PI/180;const dLng=(d-b)*Math.PI/180;const x=Math.sin(dLat/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function bearing(a,b,c,d){const y=Math.sin((d-b)*Math.PI/180)*Math.cos(c*Math.PI/180);const x=Math.cos(a*Math.PI/180)*Math.sin(c*Math.PI/180)-Math.sin(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.cos((d-b)*Math.PI/180);return (Math.atan2(y,x)*180/Math.PI+360)%360;}
const AdBar = React.memo(()=>{ return (<View style={{height:52,width:'100%',backgroundColor:'#000',borderTopWidth:1,borderColor:'#222',alignItems:'center',justifyContent:'center'}}>{BannerAd? <BannerAd unitId={BANNER_ID} size={BannerAdSize.BANNER} /> : <Text style={{color:'#666',fontSize:10}}>AD 320x50</Text>}</View>); });export default function App(){
const [track,setTrack]=useState(TRACKS[0]);const [locked,setLocked]=useState(false);const [acc,setAcc]=useState(0);const [speedMs,setSpeedMs]=useState(0);
const [running,setRunning]=useState(false);const [best,setBest]=useState(null);const [prev,setPrev]=useState(null);
const [sector,setSector]=useState([0,0,0]);const [history,setHistory]=useState([]);const [isPro,setIsPro]=useState(true);
const [tab,setTab]=useState('dash');const [showSet,setShowSet]=useState(false);const [darkMode,setDarkMode]=useState(false);const [lang,setLang]=useState('zh');
const [calibDist,setCalibDist]=useState(25);const [minTrigger,setMinTrigger]=useState(15);const [autoLap,setAutoLap]=useState(true);const [unit,setUnit]=useState('kmh');const [tempU,setTempU]=useState('C');const [tempC,setTempC]=useState(null);const [timeFmt,setTimeFmt]=useState('mm:ss');const [ghostOp,setGhostOp]=useState(0.5);const [gForce,setGForce]=useState({x:0,max:0});const [gpsHz,setGpsHz]=useState(1);const [accFilt,setAccFilt]=useState(10);const [showLabels,setShowLabels]=useState(true);const [safeMode,setSafeMode]=useState(true);
const [useFakeGps,setUseFakeGps]=useState(true);const [demoIdx,setDemoIdx]=useState(0);const [showDot,setShowDot]=useState(true);const [showGhost,setShowGhost]=useState(true);const [ghostIdx,setGhostIdx]=useState(15);const [curTime,setCurTime]=useState(0);
const startRef=useRef(0);const lastTimeRef=useRef(0);const subRef=useRef(null);const trackRef=useRef(TRACKS[0]);const runningRef=useRef(false);const maxSpeedLapRef=useRef(0);const finishLapRef=useRef(null);const lastSpeed=useRef(0);const lastManualTrack=useRef(0);const lastPos=useRef(null);const fakeTimer=useRef(null);const T=LANG[lang];
useEffect(()=>{trackRef.current=track;},[track]);
useEffect(()=>{(async()=>{
try{ if(MobileAds){ await MobileAds().initialize(); } }catch(e){}
const {status}=await Location.requestForegroundPermissionsAsync();if(status!=='granted')return;
const vals=await AsyncStorage.multiGet(['lap_history','isPro','pro_exp','darkMode','lang','calib','minTrig','autoLap','unit','tempU','timeFmt','gpsHz','accFilt','showLabels','safeMode']);const m=Object.fromEntries(vals);
if(m.lap_history)try{setHistory(JSON.parse(m.lap_history));}catch(e){};if(m.darkMode!==null)setDarkMode(m.darkMode==='1');if(m.lang)setLang(m.lang);if(m.calib)setCalibDist(parseInt(m.calib));if(m.minTrig)setMinTrigger(parseInt(m.minTrig));if(m.autoLap!==null)setAutoLap(m.autoLap==='1');if(m.unit)setUnit(m.unit);if(m.tempU)setTempU(m.tempU);if(m.timeFmt)setTimeFmt(m.timeFmt);if(m.gpsHz)setGpsHz(parseInt(m.gpsHz));if(m.accFilt)setAccFilt(parseInt(m.accFilt));if(m.showLabels!==null)setShowLabels(m.showLabels==='1');if(m.safeMode!==null)setSafeMode(m.safeMode==='1');
if(subRef.current) subRef.current.remove();
subRef.current=await Location.watchPositionAsync({accuracy:Location.Accuracy.BestForNavigation,distanceInterval:1,timeInterval:1000},loc=>{
try{
const lat=loc.coords.latitude, lng=loc.coords.longitude, accu=loc.coords.accuracy||99, spd=loc.coords.speed||0;
if(Date.now()-lastManualTrack.current>15000){
 let near=trackRef.current, minD=Infinity; TRACKS.forEach(t=>{const d=dist(lat,lng,t.lat,t.lng); if(d<minD){minD=d; near=t;}});
 if(minD<50000 && near){
  if(near.id==='tmn'||near.id==='tms'){
   if(lastPos.current && spd>1){
    const h=loc.coords.heading!=null?loc.coords.heading:bearing(lastPos.current.lat,lastPos.current.lng,lat,lng);
    if(!isNaN(h)){ near = h>=0&&h<180? TRACKS.find(t=>t.id==='tmn') : TRACKS.find(t=>t.id==='tms'); }
   }
  }
  if(near && near.id!==trackRef.current.id){ trackRef.current=near; setTrack(near); }
 }
 lastPos.current={lat,lng};
}
setAcc(accu); if(accu<100) setLocked(true); setSpeedMs(spd);
const kmhNow=spd*3.6; if(runningRef.current && kmhNow>maxSpeedLapRef.current) maxSpeedLapRef.current=kmhNow;
const g=Math.abs(spd-lastSpeed.current)*0.8; lastSpeed.current=spd; setGForce(p=>({x:g.toFixed(2),max:Math.max(g,p.max).toFixed(2)}));
if(runningRef.current&&autoLap&&finishLapRef.current&&!useFakeGps){if(dist(lat,lng,trackRef.current.lat,trackRef.current.lng)<calibDist&&Date.now()-startRef.current>minTrigger*1000)finishLapRef.current();}
}catch(e){}
});
})();return()=>{if(subRef.current)subRef.current.remove();if(fakeTimer.current)clearInterval(fakeTimer.current);};},[]);
useEffect(()=>{if(running&&useFakeGps){fakeTimer.current=setInterval(()=>{setCurTime((Date.now()-startRef.current)/1000); setDemoIdx(p=>{const n=(p+1)%97; if(n===0&&finishLapRef.current)finishLapRef.current(); return n;}); setGhostIdx(p=>(p+1)%97);},80);}else{if(fakeTimer.current)clearInterval(fakeTimer.current);}},[running,useFakeGps]);
const fmt=s=>{if(!s)return '--:--.--';if(timeFmt==='ss')return `${s.toFixed(2)}s`;const mm=Math.floor(s/60);const r=(s%60).toFixed(2);return `${mm}:${r.padStart(5,'0')}`;};
const getSpeed=()=>{if(useFakeGps&&running)return '62'; const kmh=speedMs*3.6;return unit==='kmh'?kmh.toFixed(0):(kmh*0.621371).toFixed(0);};
const getTemp=()=>{if(tempC===null)return '--';return tempU==='C'?`${tempC.toFixed(1)}°C`:`${(tempC*9/5+32).toFixed(1)}°F`;};
const getMaxDisplay=(kph)=>{if(kph===null||kph===undefined||kph===0) return '--'; const v=parseFloat(kph); if(isNaN(v)) return '--'; if(unit==='mph') return (v*0.621371).toFixed(1); return v.toFixed(1);};
useEffect(()=>{fetch(`https://api.open-meteo.com/v1/forecast?latitude=${track.lat}&longitude=${track.lng}&current=temperature_2m`).then(r=>r.json()).then(d=>{if(d.current) setTempC(d.current.temperature_2m);}).catch(e=>{});},[track.id]);
const start=()=>{ if(runningRef.current) return; startRef.current=Date.now(); lastTimeRef.current=0; maxSpeedLapRef.current=0; runningRef.current=true; setRunning(true); setCurTime(0); setGForce({x:0,max:0}); };
const stop=()=>{ runningRef.current=false; setRunning(false); lastTimeRef.current=curTime; };
const finishLap=async()=>{const t=(Date.now()-startRef.current)/1000; if(t<5)return; const s1=t*0.35,s2=t*0.34,s3=t*0.31;const isTM=trackRef.current.id==='tmn'||trackRef.current.id==='tms';const maxKphRaw=useFakeGps? 142+Math.random()*10 : maxSpeedLapRef.current; maxSpeedLapRef.current=0;
if(safeMode&&isTM){Alert.alert('安全模式',lang==='zh'?'此圈僅作訓練參考':'Training only',[{text:'知道了',style:'cancel'}],{cancelable:true});setPrev(t);setSector([s1,s2,s3]);startRef.current=Date.now();return;}
const lap={id:Date.now(),time:t,s1,s2,s3,track:trackRef.current.id,date:new Date().toISOString(),maxKph:maxKphRaw,gMax:gForce.max};let nh=[lap,...history];if(nh.length>100)nh=nh.slice(0,100);setHistory(nh);await AsyncStorage.setItem('lap_history',JSON.stringify(nh));setPrev(t);if(!best||t<best)setBest(t);setSector([s1,s2,s3]);startRef.current=Date.now(); setCurTime(0);};
useEffect(()=>{finishLapRef.current=finishLap;},[history,best,safeMode,gForce,isPro,lang]);
const save=async(k,v)=>{await AsyncStorage.setItem(k,String(v));};const theme=darkMode?darkS:lightS;
const toggleLang=async()=>{const nl=lang==='zh'?'en':'zh';setLang(nl);await save('lang',nl);};
const toggleUnit=async()=>{const nu=unit==='kmh'?'mph':'kmh';setUnit(nu);await save('unit',nu);};
const handleProToggle=(type)=>{if(type==='dot')setShowDot(v=>!v); if(type==='ghost')setShowGhost(v=>!v);};
const handleUpgrade=async()=>{Alert.alert('DEMO V3已解鎖','紅點+幽靈貼線',[{text:'OK',style:'cancel'}],{cancelable:true});};const DashContent=()=>{const path=TRACK_PATHS[track.id]||ZIC_PATH; return(<View><View style={{alignItems:'center',marginVertical:4}}><Text style={[s.big,theme.t]}>{fmt(curTime)}</Text></View><View style={s.row3}><View style={[s.b,theme.b]}><Text style={[s.l,theme.sub]}>{T.prev}</Text><Text style={[s.v,theme.t]}>{prev?fmt(prev):'--'}</Text></View><View style={[s.b,theme.b]}><Text style={[s.l,theme.sub]}>{T.best}</Text><Text style={[s.v,{color:'#00cc66'}]}>{best?fmt(best):'--'}</Text></View><View style={[s.b,theme.b]}><Text style={[s.l,theme.sub]}>{T.delta}</Text><Text style={[s.v,{color:'#00cc66'}]}>{prev&&best?`${(prev-best).toFixed(2)}`:'--'}</Text></View></View><View style={{flexDirection:'row',marginHorizontal:6,marginTop:3}}><View style={[s.dataBox,theme.b,{flex:1}]}><Text style={s.dataLabel}>{T.speed} ({unit}) {useFakeGps?'[FAKE]':''}</Text><Text style={[s.dataVal,{color:'#00e5ff'}]}>{getSpeed()}</Text></View><View style={[s.dataBox,theme.b,{flex:0.8}]}><Text style={s.dataLabel}>{T.temp}</Text><Text style={[s.dataVal,{color:'#ffaa00'}]}>{getTemp()}</Text></View><View style={[s.dataBox,theme.b,{flex:1}]}><Text style={s.dataLabel}>G / Max</Text><View style={{flexDirection:'row',justifyContent:'space-between'}}><Text style={{color:'#ffaa00',fontWeight:'bold',fontSize:13}}>{gForce.x}G</Text><Text style={{color:'#fff',fontWeight:'bold',fontSize:10}}>{gForce.max}G</Text></View><Text style={{color:'#00e5ff',fontWeight:'bold',fontSize:11,marginTop:1}}>{getMaxDisplay(maxSpeedLapRef.current)} {unit}</Text></View></View><View style={[s.mapFixed,{backgroundColor:'#000',borderColor:'#00cc66',borderWidth:1.5}]}><Image source={track.img} style={s.mapImgFixed} resizeMode="contain"/>{showGhost&&<View style={{position:'absolute',left:`${path[ghostIdx][0]*100}%`,top:`${path[ghostIdx][1]*100}%`,width:12,height:12,borderRadius:6,backgroundColor:`rgba(0,255,136,${ghostOp})`,borderWidth:1.5,borderColor:'#00ff88',transform:[{translateX:-6},{translateY:-6}]}}/>}{showDot&&<View style={{position:'absolute',left:`${path[demoIdx][0]*100}%`,top:`${path[demoIdx][1]*100}%`,width:14,height:14,borderRadius:7,backgroundColor:'#ff2222',borderWidth:2,borderColor:'#fff',transform:[{translateX:-7},{translateY:-7}],zIndex:99}}/>}{showLabels&&<Text style={s.start}>{T.sf} • {track.short} {useFakeGps?'FAKE ON':''}</Text>}</View><View style={s.row3}><View style={[s.sb,theme.b]}><Text style={[s.sbT,theme.t]}>{sector[0].toFixed(2)}</Text><Text style={s.sL}>{T.s1}</Text></View><View style={[s.sb,theme.b]}><Text style={[s.sbT,theme.t]}>{sector[1].toFixed(2)}</Text><Text style={s.sL}>{T.s2}</Text></View><View style={[s.sb,theme.b]}><Text style={[s.sbT,theme.t]}>{sector[2].toFixed(2)}</Text><Text style={s.sL}>{T.s3}</Text></View></View></View>);};
const DashView=()=>{
  return(
    <View style={{flex:1}}>
      <DashContent/>
      <View style={s.btnR}><Pressable onPress={stop} style={({pressed})=>[s.btn,{backgroundColor:running?'#ff3333':'#551111',opacity:pressed?0.7:1}]}><Text style={s.btnT}>■ STOP</Text></Pressable><Pressable onPress={start} style={({pressed})=>[s.btn,{backgroundColor:running?'#114422':'#00cc66',opacity:pressed?0.7:1}]}><Text style={s.btnT}>▶ START {useFakeGps?'FAKE V3':''}</Text></Pressable></View>
      <Text style={[s.hT,theme.t]}>{T.hist} ({history.length})</Text>
      <View style={{marginHorizontal:6,marginTop:4,borderWidth:1,borderColor:'#222',borderRadius:8,overflow:'hidden',flex:1}}>
        <View style={{flexDirection:'row',paddingVertical:5,paddingHorizontal:6,backgroundColor:'#111'}}><Text style={{flex:0.5,fontSize:9,color:'#888'}}>LAP</Text><Text style={{flex:1.1,fontSize:9,color:'#888'}}>TIME</Text><Text style={{flex:0.7,fontSize:9,color:'#888'}}>TRACK</Text><Text style={{flex:0.5,fontSize:9,color:'#888'}}>G</Text><Text style={{flex:0.6,fontSize:9,color:'#00e5ff'}}>MAX</Text></View>
        <ScrollView style={{flex:1}} bounces={false}>
          {history.map((h,i)=>{const isBest=h.time===best;return(<View key={h.id} style={[s.hR,{flexDirection:'row',alignItems:'center',backgroundColor:isBest?'#003322':'#1a1a1a',borderColor:'#222'}]}><Text style={{flex:0.5,fontSize:11,color:'#fff'}}>{history.length-i}</Text><Text style={{flex:1.1,fontSize:11,fontWeight:'bold',color:isBest?'#00ff88':'#fff'}}>{fmt(h.time)}</Text><Text style={{flex:0.7,fontSize:10,color:'#aaa'}}>{h.track.toUpperCase()}</Text><Text style={{flex:0.5,fontSize:10,color:'#aaa'}}>{h.gMax||0}G</Text><Text style={{flex:0.6,fontSize:11,fontWeight:'bold',color:'#00e5ff'}}>{getMaxDisplay(h.maxKph)}</Text></View>);})}
          {history.length===0&&<Text style={[theme.sub,{textAlign:'center',marginVertical:30}]}>未有紀錄</Text>}
        </ScrollView>
      </View>
    </View>
  );
};
return(
<View style={[s.c,theme.c]}>
<View style={[s.head,theme.head]}><View style={{flex:1}}><Text style={[s.t,theme.t]}>{T.app}</Text><Text style={[s.sub,theme.sub]} numberOfLines={1}>{lang==='zh'?track.name:track.en} • {track.short} {useFakeGps?'• FAKE ON V3':''}</Text></View><TouchableOpacity onPress={()=>setShowSet(true)} style={s.gear}><Text style={{fontSize:16}}>⚙️</Text></TouchableOpacity></View>
<View style={[s.gps,theme.gps]}><Text style={{color:locked?'#00cc66':'#ff4444',fontWeight:'bold',fontSize:11}}>{locked?T.gpsOk:T.gpsNo}</Text><Text style={[s.gpsI,theme.sub]}>{T.acc} {acc.toFixed(1)}m • {getTemp()}</Text></View>
<View style={{flex:1}}>
{tab==='dash'&&<DashView/>}
{tab==='sessions'&&<ScrollView style={{flex:1,padding:6}}>{history.map((h,i)=><View key={h.id} style={[s.hR,theme.b]}><Text style={[theme.t,{fontSize:11}]}>{history.length-i}. {h.track.toUpperCase()} • {fmt(h.time)} • {getMaxDisplay(h.maxKph)}{unit}</Text></View>)}</ScrollView>}
{tab==='tracks'&&<ScrollView style={{flex:1}} contentContainerStyle={{flexDirection:'row',flexWrap:'wrap',padding:6}}>{TRACKS.map(t=><TouchableOpacity key={t.id} onPress={()=>{setTrack(t);lastManualTrack.current=Date.now();trackRef.current=t; setTab('dash');}} style={[s.trackCard,theme.b,track.id===t.id&&{borderColor:'#00cc66',borderWidth:2}]}><Image source={t.img} style={{width:'100%',height:72,borderRadius:6}} resizeMode="contain"/><Text style={[theme.t,{fontSize:10,marginTop:3}]}>{lang==='zh'?t.name:t.en}</Text></TouchableOpacity>)}</ScrollView>}
</View>
{!isPro && <AdBar/>}<Modal visible={showSet} animationType="slide"><View style={[s.setPage,theme.c]}><ScrollView style={{padding:14,paddingTop:8}}><View style={{flexDirection:'row',justifyContent:'space-between',marginBottom:8,marginTop:4}}><Text style={[{fontSize:15,fontWeight:'bold'},theme.t]}>{T.set} V3貼線版</Text><TouchableOpacity onPress={()=>setShowSet(false)}><Text style={[{fontSize:18},theme.t]}>✕</Text></TouchableOpacity></View>
<View style={[s.proCard,{backgroundColor:'#111'}]}><Text style={{fontWeight:'bold',color:'#ffaa00',fontSize:12}}>👑 {T.proOn}</Text><Text style={{fontSize:9,color:'#fff',marginTop:2}}>{T.proDesc}</Text></View>
<Text style={[s.setTitle,theme.t]}>{T.timer}</Text><TouchableOpacity style={[s.setRow,theme.b]} onPress={()=>{const nv=calibDist>=50?10:calibDist+5;setCalibDist(nv);save('calib',nv);}}><Text style={theme.t}>{T.calib} {calibDist}m</Text><Text style={theme.sub}>{calibDist}m ＞</Text></TouchableOpacity><TouchableOpacity style={[s.setRow,theme.b]} onPress={()=>{const nv=minTrigger>=30?5:minTrigger+5;setMinTrigger(nv);save('minTrig',nv);}}><Text style={theme.t}>{T.minTrig} {minTrigger}s</Text><Text style={theme.sub}>{minTrigger}s ＞</Text></TouchableOpacity><View style={[s.setRow,theme.b]}><Text style={theme.t}>{T.autoLap}</Text><Switch value={autoLap} onValueChange={v=>{setAutoLap(v);save('autoLap',v?'1':'0');}}/></View><TouchableOpacity style={[s.setRow,theme.b]} onPress={()=>{const opts=[1,5,10];const idx=opts.indexOf(gpsHz);const nv=opts[(idx+1)%opts.length];setGpsHz(nv);save('gpsHz',nv);}}><Text style={theme.t}>{T.gpsHz}</Text><Text style={[theme.t,{color:'#00cc66',fontWeight:'bold'}]}>{gpsHz}Hz ＞</Text></TouchableOpacity><TouchableOpacity style={[s.setRow,theme.b]} onPress={()=>{const nv=accFilt>=10?3:accFilt+2;setAccFilt(nv);save('accFilt',nv);}}><Text style={theme.t}>{T.accFilt}</Text><Text style={theme.sub}>＜{accFilt}m ＞</Text></TouchableOpacity>
<Text style={[s.setTitle,theme.t]}>DEMO假GPS (V3貼線)</Text><View style={[s.setRow,theme.b]}><Text style={theme.t}>假GPS試跑 {useFakeGps?'ON 貼線':'OFF'}</Text><Switch value={useFakeGps} onValueChange={v=>setUseFakeGps(v)}/></View>
<Text style={[s.setTitle,theme.t]}>{T.disp}</Text><View style={[s.setRow,theme.b]}><Text style={theme.t}>{T.night}</Text><Switch value={darkMode} onValueChange={v=>{setDarkMode(v);save('darkMode',v?'1':'0');}}/></View><TouchableOpacity style={[s.setRow,theme.b]} onPress={toggleLang}><Text style={theme.t}>{T.langTitle}</Text><Text style={[theme.t,{fontWeight:'bold',color:'#00cc66'}]}>{lang==='zh'?'中文':'EN'} ↔</Text></TouchableOpacity><TouchableOpacity style={[s.setRow,theme.b]} onPress={toggleUnit}><Text style={theme.t}>{T.unit}</Text><Text style={[theme.t,{fontWeight:'bold',color:'#00cc66'}]}>{unit.toUpperCase()} ↔</Text></TouchableOpacity><TouchableOpacity style={[s.setRow,theme.b]} onPress={async()=>{const nv=tempU==='C'?'F':'C';setTempU(nv);await save('tempU',nv);}}><Text style={theme.t}>{T.tempUnit} {getTemp()}</Text><Text style={[theme.t,{fontWeight:'bold',color:'#00cc66'}]}>°{tempU} ↔</Text></TouchableOpacity><TouchableOpacity style={[s.setRow,theme.b]} onPress={async()=>{const nv=timeFmt==='mm:ss'?'ss':'mm:ss';setTimeFmt(nv);await save('timeFmt',nv);}}><Text style={theme.t}>{T.timeFmt}</Text><Text style={[theme.t,{fontWeight:'bold',color:'#00cc66'}]}>{timeFmt} ↔</Text></TouchableOpacity><View style={[s.setRow,theme.b]}><Text style={theme.t}>{T.labels}</Text><Switch value={showLabels} onValueChange={v=>{setShowLabels(v);save('showLabels',v?'1':'0');}}/></View><View style={[s.setRow,theme.b]}><Text style={theme.t}>安全模式</Text><Switch value={safeMode} onValueChange={v=>{setSafeMode(v);save('safeMode',v?'1':'0');}}/></View>
<Text style={[s.setTitle,theme.t]}>{T.proF} (V3已解鎖)</Text><TouchableOpacity style={[s.setRow,theme.b]} onPress={()=>handleProToggle('dot')}><Text style={theme.t}>{T.dot} {showDot?'● ON':'○ OFF'}</Text><Text style={[theme.t,{color:'#00cc66'}]}>{showDot?'紅點開':'紅點關'} ＞</Text></TouchableOpacity><TouchableOpacity style={[s.setRow,theme.b]} onPress={()=>handleProToggle('ghost')}><Text style={theme.t}>{T.ghost} {Math.round(ghostOp*100)}% {showGhost?'ON':'OFF'}</Text><Text style={[theme.t,{color:'#00cc66'}]}>幽靈{showGhost?'開':'關'} ＞</Text></TouchableOpacity><TouchableOpacity style={[s.setRow,theme.b]} onPress={()=>{const nv=ghostOp>=1?0.2:ghostOp+0.2; setGhostOp(nv);}}><Text style={theme.t}>{T.ghost} 透明度</Text><Text style={[theme.t,{color:'#00cc66'}]}>{Math.round(ghostOp*100)}% ＞</Text></TouchableOpacity>
<Text style={[s.setTitle,theme.t]}>{T.sys}</Text><TouchableOpacity style={[s.setRow,theme.b]} onPress={()=>{Alert.alert('清除紀錄','確定清晒所有圈速？',[{text:'取消',style:'cancel'},{text:'確定清除',style:'destructive',onPress:async()=>{await AsyncStorage.multiRemove(['lap_history']);setHistory([]);}}],{cancelable:true});}}><Text style={theme.t}>{T.clear}</Text><Text style={theme.sub}>＞</Text></TouchableOpacity>
<Text style={[s.setTitle,theme.t]}>{T.about}</Text><TouchableOpacity style={[s.setRow,theme.b]} onPress={()=>Alert.alert(T.disclaimer,T.disTxt,[{text:'知道了',style:'cancel'}],{cancelable:true})}><Text style={theme.t}>{T.disclaimer}</Text><Text style={theme.sub}>＞</Text></TouchableOpacity><TouchableOpacity style={[s.setRow,theme.b]} onPress={()=>Alert.alert(T.privacy,T.priTxt,[{text:'知道了',style:'cancel'}],{cancelable:true})}><Text style={theme.t}>{T.privacy}</Text><Text style={theme.sub}>＞</Text></TouchableOpacity><TouchableOpacity style={[s.setRow,theme.b]} onPress={()=>Alert.alert(T.contact,T.conTxt,[{text:'知道了',style:'cancel'}],{cancelable:true})}><Text style={theme.t}>{T.contact}</Text><Text style={theme.sub}>＞</Text></TouchableOpacity>
<View style={{alignItems:'center',marginTop:14,marginBottom:10}}><Text style={{fontSize:11,color:'#888'}}>v1.0 V3 貼線版 • 唔出界 • 計時正常</Text></View>
</ScrollView></View></Modal>
<View style={[s.tabBar,theme.gps]}><TouchableOpacity style={s.tabBtn} onPress={()=>setTab('dash')}><Text style={[s.tab,tab==='dash'&&s.tabOn]}>{T.dash}</Text></TouchableOpacity><TouchableOpacity style={s.tabBtn} onPress={()=>setTab('sessions')}><Text style={[s.tab,tab==='sessions'&&s.tabOn]}>{T.sess}</Text></TouchableOpacity><TouchableOpacity style={s.tabBtn} onPress={()=>setTab('tracks')}><Text style={[s.tab,tab==='tracks'&&s.tabOn]}>{T.tracks}</Text></TouchableOpacity></View>
</View>);}
const s=StyleSheet.create({c:{flex:1,paddingTop:0},head:{flexDirection:'row',justifyContent:'space-between',paddingHorizontal:10,paddingTop:8,paddingBottom:4,alignItems:'center'},t:{fontSize:15,fontWeight:'bold'},sub:{fontSize:10},gear:{padding:4},proCard:{backgroundColor:'#fff3cd',padding:8,borderRadius:8,marginTop:6,borderWidth:1,borderColor:'#ffaa00'},upBtn:{backgroundColor:'#111',padding:7,borderRadius:6,marginTop:5},gps:{flexDirection:'row',justifyContent:'space-between',paddingHorizontal:10,paddingVertical:3},gpsI:{fontSize:10},big:{fontSize:36,textAlign:'center',fontWeight:'bold',marginVertical:2},row3:{flexDirection:'row',justifyContent:'space-around'},b:{paddingVertical:2,paddingHorizontal:6,borderRadius:6,flex:1,margin:2,height:40,justifyContent:'center',alignItems:'center',borderWidth:1},l:{fontSize:9,color:'#888'},v:{fontSize:13,fontWeight:'bold'},dataBox:{paddingVertical:2,paddingHorizontal:6,borderRadius:6,margin:2,height:48,justifyContent:'center',borderWidth:1},dataLabel:{fontSize:9,color:'#888'},dataVal:{fontSize:17,fontWeight:'bold'},mapFixed:{height:165,marginHorizontal:6,marginVertical:3,borderRadius:10,overflow:'hidden',borderWidth:1.5,backgroundColor:'#000',justifyContent:'center',alignItems:'center'},mapImgFixed:{width:'100%',height:'100%'},start:{position:'absolute',bottom:4,left:6,color:'#fff',fontSize:9,backgroundColor:'rgba(0,0,0,0.7)',paddingHorizontal:5,paddingVertical:1,borderRadius:4},sb:{paddingVertical:2,borderRadius:6,flex:1,margin:2,height:38,justifyContent:'center',alignItems:'center',borderWidth:1},sbT:{fontSize:12,fontWeight:'bold'},sL:{backgroundColor:'#00cc66',color:'#fff',paddingHorizontal:5,borderRadius:4,marginTop:1,fontSize:9,fontWeight:'bold'},hT:{fontSize:11,marginHorizontal:8,marginTop:6,fontWeight:'bold'},hR:{padding:5,marginHorizontal:6,marginVertical:1.5,borderRadius:5,borderWidth:1},btnR:{flexDirection:'row',justifyContent:'space-around',marginHorizontal:8,marginVertical:6},btn:{padding:11,borderRadius:7,flex:1,margin:2,alignItems:'center'},btnT:{color:'#fff',fontWeight:'bold',fontSize:14},tabBar:{flexDirection:'row',justifyContent:'space-around',paddingVertical:10,borderTopWidth:1},tabBtn:{flex:1,alignItems:'center'},tab:{color:'#888',fontSize:12},tabOn:{color:'#00cc66',fontWeight:'bold',fontSize:13},setPage:{flex:1},setTitle:{fontWeight:'bold',marginTop:12,marginBottom:4,fontSize:10,color:'#00cc66'},setRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',padding:11,borderRadius:8,marginBottom:6,borderWidth:1},trackCard:{width:'47%',margin:'1.5%',padding:6,borderRadius:8,borderWidth:1}});
const lightS=StyleSheet.create({c:{backgroundColor:'#f5f5f5'},head:{backgroundColor:'#fff'},t:{color:'#111'},sub:{color:'#666'},gps:{backgroundColor:'#eee',borderTopWidth:1,borderColor:'#ddd'},b:{backgroundColor:'#fff',borderColor:'#e0e0e0'},map:{backgroundColor:'#000',borderColor:'#333'}});
const darkS=StyleSheet.create({c:{backgroundColor:'#000'},head:{backgroundColor:'#000'},t:{color:'#fff'},sub:{color:'#aaa'},gps:{backgroundColor:'#111',borderTopWidth:1,borderColor:'#333'},b:{backgroundColor:'#111',borderColor:'#333'},map:{backgroundColor:'#000',borderColor:'#00cc66'}});
