name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }} # 使用你之前設定的 EXPO_TOKEN
          packager: npm # 強制使用 npm，不使用 yarn，提高穩定性

      - name: Install dependencies
        run: npm install

      - name: Build APK (Preview)
        run: eas build --platform android --profile preview --non-interactive
